version: "3.7"
services:
  anyApp:
    image: ${DOCKER_REPO:-jeissonosorio}/${PROJECT_LANG:-python}-expert:v1.0
    build:
      context: src/${PROJECT_LANG:-python}
    ports:
      - ${EXPOSE_PORT:-8080}:8080