FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html

# sudo docker build -t "bootcampnginx:v1.0" .
# sudo docker run -it --name bootcampnginx bootcampnginx:v1.0
# sudo docker run --rm -it --name bootcampnginx bootcampnginx:v1.0
