---
kind: Service
apiVersion: v1
metadata:
  name:  kontinu-app
  annotations:
    description: "mi servicio"

spec:
  selector:
    app: kontinu-app
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  http
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontinu-app
  labels:
    name: kontinu-app
spec:
  #? deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  replicas: 3
  selector:
    matchLabels: #! && (AND)
      app: kontinu-app
  template:
    #* pod template
    metadata:
      labels:
        app: kontinu-app
    spec:
      containers:
      - name: kontinu-app


        env:
          - name: FOO
            value: "Hello From K8s ⌛"

        image: kontinu/python-expert:v1.0

        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 8080

...

